"""Add notifications and push subscriptions

Revision ID: a438085fcc89
Revises: 83ff3c53dab0
Create Date: 2026-07-05 16:33:32.228331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a438085fcc89'
down_revision: Union[str, Sequence[str], None] = '83ff3c53dab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.drop_index(op.f('idx_feedback_user'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('idx_conv_session'), table_name='conversations')
    op.drop_index(op.f('idx_conv_user'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_style', sa.TEXT(), server_default=sa.text("'balanced'::text"), autoincrement=False, nullable=True),
    sa.Column('prefers_charts', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('top_interests', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('corrections', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('disliked_intents', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_preferences_pkey'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("role = ANY (ARRAY['user'::text, 'assistant'::text])", name=op.f('conversations_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('idx_conv_user'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conv_session'), 'conversations', ['session_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("rating = ANY (ARRAY['up'::text, 'down'::text])", name=op.f('feedback_rating_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('idx_feedback_user'), 'feedback', ['user_id'], unique=False)
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
